# Form implementation generated from reading ui file 'dieukhoan.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 328)
        MainWindow.setStyleSheet("border-image: url(:/dieukhoan/KTLT(5).png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ptndongy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptndongy.setGeometry(QtCore.QRect(270, 260, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ptndongy.setFont(font)
        self.ptndongy.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ptndongy.setObjectName("ptndongy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ptndongy.setText(_translate("MainWindow", "Tôi đã đọc và đồng ý với các điều khoản thuê sách"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
