# Form implementation generated from reading ui file 'giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 329)
        MainWindow.setStyleSheet("border-image: url(:/pic/KTLT(1).png);\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblHoTen = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblHoTen.setGeometry(QtCore.QRect(220, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblHoTen.setFont(font)
        self.lblHoTen.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblHoTen.setObjectName("lblHoTen")
        self.lblSdt = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSdt.setGeometry(QtCore.QRect(220, 130, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblSdt.setFont(font)
        self.lblSdt.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblSdt.setObjectName("lblSdt")
        self.lblCCCD = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCCCD.setGeometry(QtCore.QRect(220, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCCCD.setFont(font)
        self.lblCCCD.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblCCCD.setObjectName("lblCCCD")
        self.lblTensach = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTensach.setGeometry(QtCore.QRect(220, 190, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTensach.setFont(font)
        self.lblTensach.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblTensach.setObjectName("lblTensach")
        self.lblMasach = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblMasach.setGeometry(QtCore.QRect(220, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblMasach.setFont(font)
        self.lblMasach.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblMasach.setObjectName("lblMasach")
        self.lblDiachi = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblDiachi.setGeometry(QtCore.QRect(220, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblDiachi.setFont(font)
        self.lblDiachi.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblDiachi.setObjectName("lblDiachi")
        self.ledHovaTen = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledHovaTen.setGeometry(QtCore.QRect(320, 100, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ledHovaTen.setFont(font)
        self.ledHovaTen.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledHovaTen.setText("")
        self.ledHovaTen.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ledHovaTen.setObjectName("ledHovaTen")
        self.ledSdt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledSdt.setGeometry(QtCore.QRect(320, 130, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ledSdt.setFont(font)
        self.ledSdt.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ledSdt.setText("")
        self.ledSdt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ledSdt.setObjectName("ledSdt")
        self.ledCCCD = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledCCCD.setGeometry(QtCore.QRect(320, 160, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ledCCCD.setFont(font)
        self.ledCCCD.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledCCCD.setText("")
        self.ledCCCD.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ledCCCD.setObjectName("ledCCCD")
        self.ledTensach = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledTensach.setGeometry(QtCore.QRect(320, 190, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ledTensach.setFont(font)
        self.ledTensach.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ledTensach.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ledTensach.setObjectName("ledTensach")
        self.ledMasach = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledMasach.setGeometry(QtCore.QRect(320, 220, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ledMasach.setFont(font)
        self.ledMasach.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledMasach.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ledMasach.setObjectName("ledMasach")
        self.ledDiachi = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledDiachi.setGeometry(QtCore.QRect(320, 250, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ledDiachi.setFont(font)
        self.ledDiachi.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ledDiachi.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ledDiachi.setObjectName("ledDiachi")
        self.ptnxacnhan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptnxacnhan.setGeometry(QtCore.QRect(420, 279, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ptnxacnhan.setFont(font)
        self.ptnxacnhan.setStyleSheet("border-image: none;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(0, 170, 255);\n"
"")
        self.ptnxacnhan.setObjectName("ptnxacnhan")
        self.ptnquaylai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptnquaylai.setGeometry(QtCore.QRect(325, 280, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.ptnquaylai.setFont(font)
        self.ptnquaylai.setStyleSheet("border-image: none;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(0, 170, 255);\n"
"")
        self.ptnquaylai.setObjectName("ptnquaylai")
        self.lblSdt.raise_()
        self.lblCCCD.raise_()
        self.lblTensach.raise_()
        self.lblMasach.raise_()
        self.lblDiachi.raise_()
        self.ledHovaTen.raise_()
        self.ledSdt.raise_()
        self.ledCCCD.raise_()
        self.ledTensach.raise_()
        self.ledMasach.raise_()
        self.ledDiachi.raise_()
        self.lblHoTen.raise_()
        self.ptnxacnhan.raise_()
        self.ptnquaylai.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblHoTen.setText(_translate("MainWindow", "Họ và Tên:"))
        self.lblSdt.setText(_translate("MainWindow", "Số điện thoại:"))
        self.lblCCCD.setText(_translate("MainWindow", "CCCD/CMT:"))
        self.lblTensach.setText(_translate("MainWindow", "Tên sách:"))
        self.lblMasach.setText(_translate("MainWindow", "Mã sách:"))
        self.lblDiachi.setText(_translate("MainWindow", "Địa chỉ:"))
        self.ptnxacnhan.setText(_translate("MainWindow", "Xác nhận"))
        self.ptnquaylai.setText(_translate("MainWindow", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
