# Form implementation generated from reading ui file 'giaodien2.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 329)
        MainWindow.setStyleSheet("border-image: url(:/pic1/KTLT(3).png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblNgaythue = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNgaythue.setGeometry(QtCore.QRect(210, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNgaythue.setFont(font)
        self.lblNgaythue.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblNgaythue.setObjectName("lblNgaythue")
        self.lblNgaytra = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNgaytra.setGeometry(QtCore.QRect(210, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNgaytra.setFont(font)
        self.lblNgaytra.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblNgaytra.setObjectName("lblNgaytra")
        self.lblSongaythue = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSongaythue.setGeometry(QtCore.QRect(380, 100, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblSongaythue.setFont(font)
        self.lblSongaythue.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblSongaythue.setObjectName("lblSongaythue")
        self.lblTongtien = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTongtien.setGeometry(QtCore.QRect(380, 130, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTongtien.setFont(font)
        self.lblTongtien.setStyleSheet("border-image: none;\n"
"color: rgb(78, 10, 127);")
        self.lblTongtien.setObjectName("lblTongtien")
        self.ledTongtien = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledTongtien.setGeometry(QtCore.QRect(450, 130, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.ledTongtien.setFont(font)
        self.ledTongtien.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledTongtien.setText("")
        self.ledTongtien.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ledTongtien.setObjectName("ledTongtien")
        self.ptnThanhtoan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptnThanhtoan.setGeometry(QtCore.QRect(340, 290, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ptnThanhtoan.setFont(font)
        self.ptnThanhtoan.setStyleSheet("border-image: none;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(0, 170, 255);\n"
"")
        self.ptnThanhtoan.setObjectName("ptnThanhtoan")
        self.ledngaythue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledngaythue.setGeometry(QtCore.QRect(280, 100, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.ledngaythue.setFont(font)
        self.ledngaythue.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledngaythue.setObjectName("ledngaythue")
        self.ledngaytra = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledngaytra.setGeometry(QtCore.QRect(280, 130, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.ledngaytra.setFont(font)
        self.ledngaytra.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ledngaytra.setObjectName("ledngaytra")
        self.ledsongaythue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledsongaythue.setGeometry(QtCore.QRect(470, 100, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.ledsongaythue.setFont(font)
        self.ledsongaythue.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ledsongaythue.setObjectName("ledsongaythue")
        self.ptnquaylai2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptnquaylai2.setGeometry(QtCore.QRect(70, 290, 56, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ptnquaylai2.setFont(font)
        self.ptnquaylai2.setStyleSheet("border-image: none;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(0, 170, 255);\n"
"")
        self.ptnquaylai2.setObjectName("ptnquaylai2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblNgaythue.setText(_translate("MainWindow", "Ngày thuê:"))
        self.lblNgaytra.setText(_translate("MainWindow", "Ngày trả:"))
        self.lblSongaythue.setText(_translate("MainWindow", "Số ngày thuê:"))
        self.lblTongtien.setText(_translate("MainWindow", "Tổng tiền:"))
        self.ptnThanhtoan.setText(_translate("MainWindow", "THANH TOÁN"))
        self.ptnquaylai2.setText(_translate("MainWindow", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
