# Form implementation generated from reading ui file 'phieunopphat.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 350)
        MainWindow.setStyleSheet("border-image: url(:/phieunopphat/KTLT(7).png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblhoten = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblhoten.setGeometry(QtCore.QRect(230, 80, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblhoten.setFont(font)
        self.lblhoten.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblhoten.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblhoten.setObjectName("lblhoten")
        self.lblsdt = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblsdt.setGeometry(QtCore.QRect(230, 100, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblsdt.setFont(font)
        self.lblsdt.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblsdt.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblsdt.setObjectName("lblsdt")
        self.lbltensach = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbltensach.setGeometry(QtCore.QRect(230, 120, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbltensach.setFont(font)
        self.lbltensach.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lbltensach.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbltensach.setObjectName("lbltensach")
        self.lblmasach = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblmasach.setGeometry(QtCore.QRect(230, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblmasach.setFont(font)
        self.lblmasach.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblmasach.setObjectName("lblmasach")
        self.lblngaytradk = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblngaytradk.setGeometry(QtCore.QRect(230, 180, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblngaytradk.setFont(font)
        self.lblngaytradk.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblngaytradk.setObjectName("lblngaytradk")
        self.lblngaytratt = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblngaytratt.setGeometry(QtCore.QRect(230, 200, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblngaytratt.setFont(font)
        self.lblngaytratt.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblngaytratt.setObjectName("lblngaytratt")
        self.lblngaymuon = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblngaymuon.setGeometry(QtCore.QRect(230, 160, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblngaymuon.setFont(font)
        self.lblngaymuon.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblngaymuon.setObjectName("lblngaymuon")
        self.lblsongayquahan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblsongayquahan.setGeometry(QtCore.QRect(230, 220, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblsongayquahan.setFont(font)
        self.lblsongayquahan.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblsongayquahan.setObjectName("lblsongayquahan")
        self.lblsotiencantra = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblsotiencantra.setGeometry(QtCore.QRect(230, 240, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblsotiencantra.setFont(font)
        self.lblsotiencantra.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblsotiencantra.setObjectName("lblsotiencantra")
        self.lbltienphuthu = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbltienphuthu.setGeometry(QtCore.QRect(220, 250, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbltienphuthu.setFont(font)
        self.lbltienphuthu.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lbltienphuthu.setObjectName("lbltienphuthu")
        self.ptnThanhtoan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptnThanhtoan.setGeometry(QtCore.QRect(320, 280, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ptnThanhtoan.setFont(font)
        self.ptnThanhtoan.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ptnThanhtoan.setObjectName("ptnThanhtoan")
        self.ledHoten = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledHoten.setGeometry(QtCore.QRect(350, 80, 131, 16))
        self.ledHoten.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledHoten.setObjectName("ledHoten")
        self.ledSdt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledSdt.setGeometry(QtCore.QRect(350, 100, 131, 16))
        self.ledSdt.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledSdt.setObjectName("ledSdt")
        self.ledTensach = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledTensach.setGeometry(QtCore.QRect(350, 120, 131, 16))
        self.ledTensach.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledTensach.setObjectName("ledTensach")
        self.ledMasach = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledMasach.setGeometry(QtCore.QRect(350, 140, 131, 16))
        self.ledMasach.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledMasach.setObjectName("ledMasach")
        self.ledNgaymuon = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledNgaymuon.setGeometry(QtCore.QRect(350, 160, 131, 16))
        self.ledNgaymuon.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledNgaymuon.setObjectName("ledNgaymuon")
        self.ledNgaytratt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledNgaytratt.setGeometry(QtCore.QRect(350, 200, 131, 16))
        self.ledNgaytratt.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledNgaytratt.setObjectName("ledNgaytratt")
        self.ledSotiencantra = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledSotiencantra.setGeometry(QtCore.QRect(350, 240, 131, 16))
        self.ledSotiencantra.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledSotiencantra.setObjectName("ledSotiencantra")
        self.ledNgaytradk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledNgaytradk.setGeometry(QtCore.QRect(350, 180, 131, 16))
        self.ledNgaytradk.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledNgaytradk.setObjectName("ledNgaytradk")
        self.ledSongayquahan = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ledSongayquahan.setGeometry(QtCore.QRect(350, 220, 131, 16))
        self.ledSongayquahan.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(78, 10, 127);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.ledSongayquahan.setObjectName("ledSongayquahan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblhoten.setText(_translate("MainWindow", "Họ & Tên:"))
        self.lblsdt.setText(_translate("MainWindow", "SĐT:"))
        self.lbltensach.setText(_translate("MainWindow", "Tên sách:"))
        self.lblmasach.setText(_translate("MainWindow", "Mã sách:"))
        self.lblngaytradk.setText(_translate("MainWindow", "Ngày trả dự kiến:"))
        self.lblngaytratt.setText(_translate("MainWindow", "Ngày trả thực tế:"))
        self.lblngaymuon.setText(_translate("MainWindow", "Ngày mượn:"))
        self.lblsongayquahan.setText(_translate("MainWindow", "Số ngày quá hạn:"))
        self.lblsotiencantra.setText(_translate("MainWindow", "Số tiền cần trả:"))
        self.lbltienphuthu.setText(_translate("MainWindow", "Cửa hàng phụ thu 10.000 VNĐ trên mỗi ngày trả quá hạn "))
        self.ptnThanhtoan.setText(_translate("MainWindow", "THANH TOÁN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
