# Form implementation generated from reading ui file 'thanhtoan1.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 328)
        MainWindow.setStyleSheet("border-image: url(:/thanhtoan/KTLT(6).png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblchuyencuphap = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblchuyencuphap.setGeometry(QtCore.QRect(250, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblchuyencuphap.setFont(font)
        self.lblchuyencuphap.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblchuyencuphap.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblchuyencuphap.setObjectName("lblchuyencuphap")
        self.lblstk = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblstk.setGeometry(QtCore.QRect(250, 130, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblstk.setFont(font)
        self.lblstk.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);\n"
"")
        self.lblstk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblstk.setObjectName("lblstk")
        self.lbltentk = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbltentk.setGeometry(QtCore.QRect(250, 150, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltentk.setFont(font)
        self.lbltentk.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lbltentk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbltentk.setObjectName("lbltentk")
        self.lbltennganhang = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbltennganhang.setGeometry(QtCore.QRect(250, 170, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltennganhang.setFont(font)
        self.lbltennganhang.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lbltennganhang.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbltennganhang.setObjectName("lbltennganhang")
        self.ptnthanhtoan1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptnthanhtoan1.setGeometry(QtCore.QRect(310, 260, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ptnthanhtoan1.setFont(font)
        self.ptnthanhtoan1.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ptnthanhtoan1.setObjectName("ptnthanhtoan1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblchuyencuphap.setText(_translate("MainWindow", "Quý khách vui lòng chuyển đúng cú pháp:"))
        self.lblstk.setText(_translate("MainWindow", "SỐ TÀI KHOẢN: 1130658779"))
        self.lbltentk.setText(_translate("MainWindow", "TÊN TÀI KHOẢN: BOOKFLOW"))
        self.lbltennganhang.setText(_translate("MainWindow", "NGÂN HÀNG: VIETCOMBANK"))
        self.ptnthanhtoan1.setText(_translate("MainWindow", "ĐÃ THANH TOÁN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
