# Form implementation generated from reading ui file 'thanhtoan2.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 348)
        MainWindow.setStyleSheet("border-image: url(:/thanhtoan2/KTLT(8).png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblcuphap = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblcuphap.setGeometry(QtCore.QRect(250, 90, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblcuphap.setFont(font)
        self.lblcuphap.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblcuphap.setObjectName("lblcuphap")
        self.lblstk = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblstk.setGeometry(QtCore.QRect(260, 170, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblstk.setFont(font)
        self.lblstk.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblstk.setObjectName("lblstk")
        self.lbltentk = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbltentk.setGeometry(QtCore.QRect(260, 190, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbltentk.setFont(font)
        self.lbltentk.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lbltentk.setObjectName("lbltentk")
        self.lblnganhang = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblnganhang.setGeometry(QtCore.QRect(260, 220, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblnganhang.setFont(font)
        self.lblnganhang.setStyleSheet("border-image: none;\n"
"color: rgb(0, 0, 127);")
        self.lblnganhang.setObjectName("lblnganhang")
        self.ptndathanhtoan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ptndathanhtoan.setGeometry(QtCore.QRect(320, 280, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ptndathanhtoan.setFont(font)
        self.ptndathanhtoan.setStyleSheet("border-image: none;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(78, 10, 127);\n"
"background-color: rgb(78, 10, 127);")
        self.ptndathanhtoan.setObjectName("ptndathanhtoan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblcuphap.setText(_translate("MainWindow", "Quý khách vui lòng chuyển đúng cú pháp"))
        self.lblstk.setText(_translate("MainWindow", "SỐ TÀI KHOẢN: 1130658779"))
        self.lbltentk.setText(_translate("MainWindow", "TÊN TÀI KHOẢN: BOOKFLOW"))
        self.lblnganhang.setText(_translate("MainWindow", "NGÂN HÀNG: VIETCOMBANK"))
        self.ptndathanhtoan.setText(_translate("MainWindow", "ĐÃ THANHN TOÁN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
